module.exports = {
  // simple vowels
  ㅏ: { rr: "a", mr: "a" },
  ㅓ: { rr: "eo", mr: "ŏ" },
  ㅗ: { rr: "o", mr: "o" },
  ㅜ: { rr: "u" },
  ㅡ: { rr: "eu", mr: "ŭ" },
  ㅣ: { rr: "i" },
  ㅐ: { rr: "ae", mr: "ae" },
  ㅔ: { rr: "e", mr: "e" },
  ㅚ: { rr: "oe" },
  ㅟ: { rr: "w" },
  // Diphtongs
  ㅑ: { rr: "ya", mr: "ya" },
  ㅕ: { rr: "yeo", mr: "yŏ" },
  ㅛ: { rr: "yo" },
  ㅠ: { rr: "yu" },
  ㅒ: { rr: "yae", mr: "yae" },
  ㅖ: { rr: "ye", mr: "ye" },
  ㅘ: { rr: "wa" },
  ㅙ: { rr: "wae" },
  ㅟ: { rr: "wi" },
  ㅝ: { rr: "wo", mr: "wŏ" },
  ㅞ: { rr: "we" },
  ㅢ: { rr: "ui", mr: "ŭi" },
  // Plosives (stops)
  ㄱ: { rr: ["g", "k"], mr: "k" },
  // ㄱ: { rr: "g" },
  ㄲ: { rr: ["kk", "k"] },
  // ㄲ: { rr: "kk" },
  ㅋ: { rr: "k" },
  ㄷ: { rr: ["d", "t"] },
  // ㄷ: { rr: "d" },
  // ㄸ: { rr: ["tt", '-'] },
  ㄸ: { rr: "tt" },
  ㅌ: { rr: "t" },
  ㅂ: { rr: ["b", "p"] },
  // ㅂ: { rr: "b" },
  ㅃ: { rr: "pp" },
  ㅍ: { rr: "p" },
  // Affricates
  ㅈ: { rr: "j" },
  ㅉ: { rr: "jj" },
  ㅊ: { rr: ["ch", "t"] },
  // ㅊ: { rr: "ch" },
  // Fricatives
  ㅅ: { rr: "s" },
  ㅆ: { rr: "ss" },
  ㅎ: { rr: "h" },
  // Nasals
  ㄴ: { rr: "n" },
  ㅁ: { rr: "m" },
  ㅇ: { rr: [null, "ng"] },
  // ㅇ: { rr: "/ng" },
  // Liquids
  ㄹ: { rr: ["r", "l"] },
  // ㄹ: { rr: "r/l" },
  // composite jamo
  ㄺ: { rr: "lg" }
};
