export declare const _table_tw: {
    readonly 罗: "羅";
    readonly 恶: "惡";
    readonly 苏: "蘇";
    readonly 馆: "館";
};
/**
 * 此表內只有符合 KEY 值時才會觸發
 */
export declare const table_jp_core: {
    readonly の: readonly ["の", "之", "的"];
    readonly と: readonly ["と", "與", "与"];
    readonly 画: readonly ["划", "画", "劃", "畫"];
    readonly 闘: readonly ["斗"];
    readonly 鬥: readonly ["斗"];
    readonly 鬭: readonly ["斗"];
    readonly 鬪: readonly ["斗"];
    readonly 闇: readonly ["暗"];
    readonly 図: readonly ["図", "圖", "图"];
    readonly 当: readonly ["当", "噹", "當", "儅"];
    readonly 閤: readonly ["合"];
    readonly 阁: readonly ["合"];
    readonly 罗: readonly ["羅", "罗", "儸", "㑩", "囉", "啰"];
    readonly 干: readonly ["幹", "乾", "干"];
    readonly 幹: readonly ["幹", "干"];
    readonly 乾: readonly ["干", "乾", "亁", "乹"];
    readonly 亁: readonly ["乾", "亁", "乹"];
    readonly 乹: readonly ["乾", "亁", "乹"];
    readonly 历: readonly ["历", "歴", "歷", "暦", "曆"];
    readonly 歴: readonly ["历"];
    readonly 歷: readonly ["历"];
    readonly 暦: readonly ["历"];
    readonly 曆: readonly ["历"];
    readonly 呻: readonly ["呻", "申"];
    readonly 覆: readonly ["覆", "复"];
    readonly 复: readonly ["覆"];
    readonly 勉: readonly ["免"];
    readonly 勉: readonly ["免"];
    readonly 甦: readonly ["甦", "蘇", "苏"];
    readonly 忧: readonly ["憂", "優"];
    readonly 鹹: readonly ["咸", "鹹"];
    readonly 准: readonly ["準", "准"];
    readonly 準: readonly ["準", "准"];
    readonly 袮: readonly ["袮", "祢"];
    readonly 儘: readonly ["儘", "侭"];
    readonly 侭: readonly ["儘", "侭"];
    readonly 脏: readonly ["脏", "髒", "臟"];
    readonly 发: readonly ["髮", "髪", "发"];
    readonly 髮: readonly ["發", "发"];
    readonly 慾: readonly ["慾", "欲"];
    readonly 讚: readonly ["讃", "讚", "贊", "赞", "賛"];
    readonly 冲: readonly ["冲", "沖", "衝"];
    readonly 面: readonly ["麵", "麪", "麺"];
    readonly 鬚: readonly ["鬚", "須", "须"];
    readonly 揹: readonly ["揹", "背"];
    readonly 捲: readonly ["捲", "卷", "巻"];
    readonly 卷: readonly ["捲", "卷", "巻", "劵", "券"];
    readonly 巻: readonly ["捲", "卷", "巻", "劵", "券"];
    readonly 苏: readonly ["苏", "蘇", "甦"];
    readonly 瀏: readonly ["瀏", "浏", "刘"];
    readonly 浏: readonly ["瀏", "浏", "刘"];
    readonly 吁: readonly ["籲", "吁"];
    readonly 囉: readonly ["囉", "啰", "罗", "羅"];
    readonly 啰: readonly ["囉", "啰", "罗", "羅"];
    readonly 修: readonly ["修", "俢"];
    readonly 犟: readonly ["犟", "強", "强"];
    readonly 嗬: readonly ["嗬", "呵"];
    readonly 唿: readonly ["唿", "呼"];
    readonly 媮: readonly ["媮", "偷"];
    readonly 采: readonly ["采", "採"];
    readonly 彩: readonly ["彩", "采"];
    readonly 𠩺: readonly ["𠩺", "釐"];
    readonly 恶: readonly ["恶", "噁", "惡"];
    readonly 炰: readonly ["炰", "炮"];
    readonly 辟: readonly ["辟", "闢", "避"];
    readonly 避: readonly ["辟", "避"];
    readonly 闢: readonly ["辟", "闢"];
    readonly 滷: readonly ["魯", "鲁"];
    readonly 鹵: readonly ["魯", "鲁"];
    readonly 卤: readonly ["魯", "鲁"];
    readonly 儓: readonly ["儓", "檯"];
    readonly 檯: readonly ["儓", "檯"];
    readonly 台: readonly ["台", "檯", "臺", "颱"];
    readonly 練: readonly ["炼"];
    readonly 练: readonly ["炼"];
    readonly 繫: readonly ["系"];
    readonly 繋: readonly ["系"];
    readonly 糓: readonly ["谷"];
    readonly 穀: readonly ["谷"];
    readonly 版: readonly ["板"];
    readonly 祕: readonly ["密"];
    readonly 秘: readonly ["密"];
    readonly 汇: readonly ["彙", "匯"];
    readonly 倂: readonly ["倂", "併"];
    readonly 併: readonly ["倂", "併"];
    readonly 幷: readonly ["并"];
    readonly 并: readonly ["幷"];
    readonly 矇: readonly ["蒙"];
    readonly 濛: readonly ["蒙"];
    readonly 懞: readonly ["蒙"];
    readonly 煇: readonly ["煇", "辉", "𪸩"];
    readonly 𪸩: readonly ["煇", "辉", "𪸩"];
    readonly 签: readonly ["籤", "簽"];
};
/**
 * 此表內符合以下任意值時會觸發
 */
export declare const table_plus_core: {
    readonly 劍: readonly ["劍", "剑", "剣", "劎", "劒", "剱", "劔"];
    readonly 砲: readonly ["砲", "炮"];
    readonly 偽: readonly ["偽", "僞"];
    readonly 內: readonly ["內", "内"];
    readonly 鬥: readonly ["鬭", "鬥", "闘", "鬪"];
    readonly 鶏: readonly ["鶏", "鷄", "雞", "鸡"];
    readonly 兎: readonly ["兎", "兔"];
    readonly 坏: readonly ["坯", "坏", "壊", "壞"];
    readonly 殻: readonly ["殻", "殼", "壳"];
    readonly 像: readonly ["像", "象"];
    readonly 蘇: readonly ["苏", "蘇", "囌"];
    readonly 館: readonly ["館", "館", "舘", "馆"];
    readonly 鳥: readonly ["鳥", "鸟", "𫠓"];
    readonly 視: readonly ["視", "視", "视", "眎"];
    readonly 険: readonly ["険", "險", "险", "嶮", "崄"];
    readonly 絶: readonly ["絶", "絕", "绝"];
    readonly 鉄: readonly ["鉄", "鐵", "铁", "鐡"];
    readonly 諸: readonly ["諸", "諸", "诸"];
    readonly 尋: readonly ["尋", "寻", "𡬶"];
    readonly 裡: readonly ["裡", "裏", "里"];
    readonly 鑑: readonly ["鑑", "鉴", "鑒"];
    readonly 麵: readonly ["麵", "麪", "麺"];
    readonly 歲: readonly ["歲", "歳", "岁"];
    readonly 鐘: readonly ["鐘", "鍾", "钟", "锺"];
    readonly 會: readonly ["會", "会", "㑹"];
    readonly 塗: readonly ["塗", "凃", "涂"];
    readonly 髮: readonly ["髮", "髪"];
    readonly 話: readonly ["話", "话", "䛡"];
    readonly 閤: readonly ["閤", "阁"];
    readonly 蔘: readonly ["蔘", "參", "参"];
    readonly 労: readonly ["労", "勞", "劳"];
    readonly 国: readonly ["国", "囯", "國"];
    readonly 罵: readonly ["罵", "骂", "駡"];
    readonly 対: readonly ["対", "對", "对"];
    readonly 鏽: readonly ["鏽", "銹", "锈"];
    readonly 駄: readonly ["駄", "䭾", "馱", "驮"];
    readonly 薩: readonly ["薩", "萨", "蕯"];
    readonly 単: readonly ["単", "單", "单"];
    readonly 継: readonly ["継", "繼", "继"];
    readonly 驗: readonly ["驗", "验", "騐", "験"];
    readonly 歴: readonly ["歴", "歷"];
    readonly 暦: readonly ["暦", "曆"];
    readonly 団: readonly ["团", "団", "團"];
    readonly 麼: readonly ["麼", "麽", "庅"];
    readonly 戰: readonly ["戦", "戰", "战"];
    readonly 乡: readonly ["郷", "鄕", "鄉", "鄊", "乡"];
    readonly 勉: readonly ["勉", "勉"];
    readonly 餘: readonly ["餘", "馀", "余"];
    readonly 網: readonly ["網", "䋄", "䋞", "网"];
    readonly 託: readonly ["託", "讬", "托"];
    readonly 纖: readonly ["纖", "纤", "縴", "繊"];
    readonly 鍊: readonly ["鍊", "錬", "𫔀", "炼", "煉"];
    readonly 擊: readonly ["撃", "擊", "击"];
    readonly 實: readonly ["實", "実", "实", "寔"];
    readonly 於: readonly ["於", "扵"];
    readonly 證: readonly ["證", "証", "证"];
    readonly 據: readonly ["據", "据", "拠"];
    readonly 處: readonly ["處", "处", "䖏", "処"];
    readonly 瞪: readonly ["瞪", "瞠", "眙"];
    readonly 肢: readonly ["肢", "胑"];
    readonly 肉: readonly ["肉", "宍", "𠕎"];
    readonly 憂: readonly ["憂", "𢝊", "𢚧", "𢟜", "懮", "𨗫"];
    readonly 繫: readonly ["繫", "繋"];
    readonly 廻: readonly ["廻", "迴"];
    readonly 録: readonly ["録", "錄", "录"];
    readonly 鎗: readonly ["鎗", "槍", "枪"];
    readonly 悠: readonly ["悠", "滺"];
    readonly 壶: readonly ["壶", "壺", "壷"];
    readonly 茲: readonly ["茲", "兹", "玆"];
    readonly 蓋: readonly ["蓋", "盖", "葢"];
    readonly 蹟: readonly ["蹟", "跡", "迹"];
    readonly 癒: readonly ["癒", "瘉"];
    readonly 辺: readonly ["辺", "邊", "边", "邉"];
    readonly 準: readonly ["準", "凖"];
    readonly 衛: readonly ["衛", "衞", "卫"];
    readonly 晚: readonly ["晚", "晩"];
    readonly 裸: readonly ["裸", "躶"];
    readonly 亀: readonly ["亀", "龜", "龟", "𪚧", "𪚿", "𠃾"];
    readonly 凼: readonly ["凼", "氹"];
    readonly 艸: readonly ["艸", "草"];
    readonly 箚: readonly ["箚", "剳"];
    readonly 复: readonly ["复", "復", "複"];
    readonly 污: readonly ["污", "汙", "汚"];
    readonly 伙: readonly ["伙", "夥"];
    readonly 御: readonly ["御", "禦"];
    readonly 鬱: readonly ["鬱", "郁"];
    readonly 淩: readonly ["淩", "凌"];
    readonly 紮: readonly ["紮", "扎"];
    readonly 痴: readonly ["痴", "癡"];
    readonly 栖: readonly ["栖", "棲"];
    readonly 犇: readonly ["犇", "奔"];
    readonly 範: readonly ["範", "范"];
    readonly 薑: readonly ["薑", "姜", "葁"];
    readonly 樸: readonly ["樸", "朴"];
    readonly 諮: readonly ["諮", "谘", "咨"];
    readonly 撚: readonly ["撚", "捻"];
    readonly 喂: readonly ["喂", "餵", "餧", "𫗭"];
    readonly 淨: readonly ["淨", "凈", "净"];
    readonly 栗: readonly ["栗", "慄"];
    readonly 挽: readonly ["挽", "輓"];
    readonly 灶: readonly ["灶", "竈"];
    readonly 線: readonly ["線", "缐", "綫", "线"];
    readonly 盡: readonly ["盡", "尽", "儘"];
    readonly 黴: readonly ["黴", "霉"];
    readonly 周: readonly ["周", "週"];
    readonly 並: readonly ["並", "并", "併"];
    readonly 讚: readonly ["讚", "讃"];
    readonly 観: readonly ["観", "觀", "观", "覌"];
    readonly 遊: readonly ["遊", "游"];
    readonly 启: readonly ["启", "啓", "啟", "啔"];
    readonly 廄: readonly ["廄", "厩", "廐", "廏"];
    readonly 氣: readonly ["気", "氣", "气"];
    readonly 欲: readonly ["慾", "欲"];
    readonly 傑: readonly ["傑", "杰"];
    readonly 鍛: readonly ["鍛", "锻", "煅"];
    readonly 徵: readonly ["徵", "徴"];
    readonly 閒: readonly ["閒", "𫔮", "閑", "闲"];
    readonly 贊: readonly ["贊", "赞", "賛"];
    readonly 櫻: readonly ["櫻", "桜", "樱"];
    readonly 尨: readonly ["尨", "狵"];
    readonly 圈: readonly ["圈", "圏"];
    readonly 凶: readonly ["凶", "兇"];
    readonly 浜: readonly ["浜", "濱", "滨"];
    readonly 煙: readonly ["煙", "烟", "菸"];
    readonly 黒: readonly ["黒", "黑"];
    readonly 樂: readonly ["樂", "乐", "楽"];
    readonly 薬: readonly ["薬", "藥", "药", "葯", "𣛙"];
    readonly 劵: readonly ["劵", "券", "卷"];
    readonly 貳: readonly ["貳", "贰", "弐", "貮", "𢎐", "二"];
    readonly 隷: readonly ["隷", "隸", "隶"];
    readonly 姫: readonly ["姫", "姬"];
    readonly 燻: readonly ["燻", "熏"];
    readonly 籲: readonly ["籲", "龥"];
    readonly 齧: readonly ["齧", "啮", "𪘂", "囓", "噛", "嚙"];
    readonly 鹼: readonly ["鹼", "碱", "硷"];
    readonly 咸: readonly ["咸", "鹹"];
    readonly 穗: readonly ["穗", "穂"];
    readonly 廢: readonly ["廢", "廃", "废"];
    readonly 蹠: readonly ["蹠", "跖"];
    readonly 吒: readonly ["吒", "咤"];
    readonly 剷: readonly ["剷", "鏟", "铲", "刬", "剗"];
    readonly 擗: readonly ["擗", "劈"];
    readonly 核: readonly ["核", "覈"];
    readonly 脣: readonly ["脣", "唇", "唇"];
    readonly 升: readonly ["升", "昇"];
    readonly 磐: readonly ["磐", "盤", "盘"];
    readonly 溪: readonly ["溪", "渓"];
    readonly 谿: readonly ["谿", "嵠"];
    readonly 折: readonly ["折", "摺"];
    readonly 祐: readonly ["祐", "佑"];
    readonly 瓮: readonly ["瓮", "罋", "甕"];
    readonly 蹤: readonly ["蹤", "踪", "踨"];
    readonly 暗: readonly ["闇", "暗"];
    readonly 昵: readonly ["昵", "暱"];
    readonly 布: readonly ["布", "佈"];
    readonly 為: readonly ["為", "为", "爲"];
    readonly 綳: readonly ["綳", "繃", "绷"];
    readonly 痺: readonly ["痺", "痹"];
    readonly 痲: readonly ["痲", "痳"];
    readonly 雇: readonly ["雇", "僱"];
    readonly 敘: readonly ["敘", "叙", "敍"];
    readonly 盪: readonly ["盪", "蕩", "荡"];
    readonly 勛: readonly ["勛", "勳", "勋", "勲"];
    readonly 祕: readonly ["祕", "秘"];
    readonly 牆: readonly ["牆", "墙", "墻"];
    readonly 爾: readonly ["爾", "尔", "尓"];
    readonly 焰: readonly ["焰", "焔"];
    readonly 默: readonly ["默", "黙"];
    readonly 壓: readonly ["壓", "压", "圧"];
    readonly 廸: readonly ["廸", "迪"];
    readonly 曉: readonly ["曉", "晓", "暁"];
    readonly 霸: readonly ["霸", "覇"];
    readonly 霊: readonly ["霊", "靈", "灵"];
    readonly 泪: readonly ["泪", "涙", "淚"];
    readonly 牺: readonly ["牺", "犠", "犧"];
    readonly 藉: readonly ["藉", "耤"];
    readonly 噸: readonly ["噸", "吨"];
    readonly 俱: readonly ["俱", "倶"];
    readonly 粽: readonly ["粽", "糉", "糭"];
    readonly 向: readonly ["向", "曏", "嚮"];
    readonly 悽: readonly ["悽", "淒", "凄"];
    readonly 鱷: readonly ["鱷", "鰐", "鳄"];
    readonly 滷: readonly ["滷", "鹵", "卤"];
    readonly 颜: readonly ["颜", "顏", "顔"];
    readonly 衝: readonly ["衝", "沖", "冲"];
    readonly 樑: readonly ["樑", "梁"];
    readonly 砂: readonly ["砂", "沙"];
    readonly 炭: readonly ["炭", "碳"];
    readonly 糸: readonly ["糸", "絲", "丝"];
    readonly 簷: readonly ["簷", "檐"];
    readonly 涌: readonly ["涌", "湧"];
    readonly 糓: readonly ["穀", "糓"];
    readonly 両: readonly ["両", "两", "兩"];
    readonly 家: readonly ["家", "傢"];
    readonly 妳: readonly ["妳", "你"];
    readonly 她: readonly ["她", "他"];
    readonly 藤: readonly ["藤", "籐", "籘"];
    readonly 嬉: readonly ["嬉", "嘻"];
    readonly 亘: readonly ["亘", "亙"];
    readonly 恆: readonly ["恆", "恒"];
    readonly 鶇: readonly ["鶇", "鶫", "鸫"];
    readonly 姉: readonly ["姉", "姐", "姊"];
    readonly 剁: readonly ["剁", "刴"];
    readonly 泄: readonly ["泄", "洩"];
    readonly 舖: readonly ["舖", "铺", "鋪", "舗"];
    readonly 效: readonly ["效", "効"];
    readonly 喻: readonly ["喻", "喩"];
    readonly 插: readonly ["挿", "插", "揷"];
    readonly 銳: readonly ["銳", "鋭", "锐"];
    readonly 權: readonly ["權", "権", "权"];
    readonly 経: readonly ["経", "經", "经"];
    readonly 歓: readonly ["歓", "歡", "欢"];
    readonly 孃: readonly ["嬢", "孃"];
    readonly 済: readonly ["済", "濟", "济"];
    readonly 收: readonly ["収", "收"];
    readonly 綠: readonly ["綠", "緑", "绿"];
    readonly 唖: readonly ["唖", "啞", "哑"];
    readonly 剿: readonly ["剿", "勦", "𠞰"];
    readonly 禍: readonly ["禍", "禍", "祸"];
    readonly 営: readonly ["營", "営", "营"];
    readonly 産: readonly ["產", "産", "产"];
    readonly 査: readonly ["查", "査"];
    readonly 絵: readonly ["繪", "絵", "绘"];
    readonly 懐: readonly ["懷", "懐", "怀"];
    readonly 釈: readonly ["釋", "釈", "释"];
    readonly 蔵: readonly ["藏", "蔵"];
    readonly 娯: readonly ["娛", "娯", "娱"];
    readonly 焼: readonly ["燒", "焼", "烧"];
    readonly 拡: readonly ["擴", "拡", "扩"];
    readonly 賎: readonly ["賤", "賎", "贱"];
    readonly 銭: readonly ["錢", "銭", "钱"];
    readonly 雑: readonly ["雜", "雑", "杂"];
    readonly 聴: readonly ["聽", "聴", "听"];
    readonly 帯: readonly ["帶", "帯", "带"];
    readonly 閲: readonly ["閲", "阅"];
    readonly 覧: readonly ["覽", "覧", "览"];
    readonly 悪: readonly ["惡", "悪", "恶"];
    readonly 亜: readonly ["亞", "亜", "亚"];
    readonly 氷: readonly ["冰", "氷"];
    readonly 县: readonly ["県", "縣", "县"];
    readonly 肅: readonly ["粛", "肅", "肃"];
    readonly 専: readonly ["專", "専", "专"];
    readonly 様: readonly ["樣", "様", "样"];
    readonly 関: readonly ["關", "関", "关"];
    readonly 檢: readonly ["検", "檢", "检"];
    readonly 侮: readonly ["侮", "侮"];
    readonly 沉: readonly ["沉", "沈"];
    readonly 嚐: readonly ["嚐", "嘗", "尝"];
    readonly 搾: readonly ["搾", "榨"];
    readonly 获: readonly ["获", "獲", "穫"];
    readonly 繮: readonly ["繮", "缰", "韁"];
    readonly 贋: readonly ["贋", "贗", "赝"];
    readonly 獃: readonly ["呆"];
    readonly 杯: readonly ["杯", "盃"];
    readonly 呪: readonly ["呪", "咒", "詋"];
    readonly 䇳: readonly ["䇳", "笺", "箋", "牋"];
    readonly 竝: readonly ["竝", "𠀤"];
    readonly 彷: readonly ["彷", "徬"];
    readonly 贑: readonly ["贑", "𫎬"];
    readonly 崖: readonly ["崖", "崕", "厓"];
    readonly 岩: readonly ["岩", "巖", "巗", "巌"];
    readonly 灕: readonly ["灕", "漓"];
    readonly 粘: readonly ["粘", "黏"];
    readonly 娴: readonly ["娴", "嫺", "嫻"];
    readonly 哗: readonly ["哗", "嘩", "譁"];
    readonly 拔: readonly ["拔", "抜"];
    readonly 湿: readonly ["湿", "溼", "濕"];
    readonly 稻: readonly ["稻", "稲"];
    readonly 楕: readonly ["楕", "椭", "橢"];
    readonly 毎: readonly ["毎", "每"];
    readonly 篦: readonly ["篦", "箆"];
    readonly 騨: readonly ["騨", "驒", "驔"];
    readonly 猛: readonly ["猛", "勐"];
    readonly 吿: readonly ["吿", "告"];
    readonly 刃: readonly ["刃", "刄"];
    readonly 教: readonly ["教", "敎"];
    readonly 蛎: readonly ["蛎", "蜊", "蠣"];
    readonly 步: readonly ["步", "歩"];
    readonly 劫: readonly ["刦", "刧", "刼", "劫"];
};
