export declare const table_voice_core: {
    readonly か: readonly ["か", "が"];
    readonly き: readonly ["き", "ぎ"];
    readonly く: readonly ["く", "ぐ"];
    readonly け: readonly ["け", "げ"];
    readonly こ: readonly ["こ", "ご"];
    readonly さ: readonly ["さ", "ざ"];
    readonly し: readonly ["し", "じ"];
    readonly す: readonly ["す", "ず"];
    readonly せ: readonly ["せ", "ぜ"];
    readonly そ: readonly ["そ", "ぞ"];
    readonly た: readonly ["た", "だ"];
    readonly ち: readonly ["ち", "ぢ"];
    readonly つ: readonly ["つ", "づ"];
    readonly て: readonly ["て", "で"];
    readonly と: readonly ["と", "ど"];
    readonly は: readonly ["は", "ば", "ぱ"];
    readonly ひ: readonly ["ひ", "び", "ぴ"];
    readonly ふ: readonly ["ふ", "ぶ", "ぷ"];
    readonly へ: readonly ["へ", "べ", "ぺ"];
    readonly ほ: readonly ["ほ", "ぼ", "ぽ"];
    readonly カ: readonly ["カ", "ガ"];
    readonly キ: readonly ["キ", "ギ"];
    readonly ク: readonly ["ク", "グ"];
    readonly ケ: readonly ["ケ", "ゲ"];
    readonly コ: readonly ["コ", "ゴ"];
    readonly サ: readonly ["サ", "ザ"];
    readonly シ: readonly ["シ", "ジ"];
    readonly ス: readonly ["ス", "ズ"];
    readonly セ: readonly ["セ", "ゼ"];
    readonly ソ: readonly ["ソ", "ゾ"];
    readonly タ: readonly ["タ", "ダ"];
    readonly チ: readonly ["チ", "ヂ"];
    readonly ツ: readonly ["ツ", "ヅ"];
    readonly テ: readonly ["テ", "デ"];
    readonly ト: readonly ["ト", "ド"];
    readonly ハ: readonly ["ハ", "バ", "パ"];
    readonly ヒ: readonly ["ヒ", "ビ", "ピ"];
    readonly フ: readonly ["フ", "ブ", "プ"];
    readonly ヘ: readonly ["ヘ", "ベ", "ペ"];
    readonly ホ: readonly ["ホ", "ボ", "ポ"];
};
